#!/bin/bash

# Import n8n workflows manually via browser

echo "🚀 Medicine Automation - n8n Workflow Importer"
echo "=============================================="
echo ""
echo "✅ n8n is running at: http://localhost:5678"
echo ""
echo "📥 IMPORT WORKFLOWS:"
echo ""
echo "Step 1: Open n8n"
echo "  → Go to: http://localhost:5678"
echo "  → Login: admin / medicine2025secure"
echo ""
echo "Step 2: Import Discovery Workflow"
echo "  1. Click 'Workflows' in left sidebar"
echo "  2. Click 'Import from File' (top right)"
echo "  3. Navigate to: ~/medicine/n8n/workflows/01-content-discovery.json"
echo "  4. Click 'Import'"
echo ""
echo "Step 3: Import Processing Workflow"
echo "  1. Click 'Workflows' in left sidebar"
echo "  2. Click 'Import from File' (top right)"
echo "  3. Navigate to: ~/medicine/n8n/workflows/02-content-processing-OLLAMA.json"
echo "  4. Click 'Import'"
echo ""
echo "Step 4: Verify Workflows"
echo "  You should see 2 workflows:"
echo "  ✓ 01 - Archive.org Content Discovery"
echo "  ✓ 02 - AI Content Processing & Script Generation"
echo ""
echo "Step 5: Test Discovery Workflow"
echo "  1. Click on: '01 - Archive.org Content Discovery'"
echo "  2. Click 'Execute Workflow' button (▶️)"
echo "  3. Wait 30-60 seconds"
echo "  4. Check results: cat ~/medicine/data/discovered-books.jsonl"
echo ""
echo "Step 6: Test Processing Workflow"
echo "  1. Click on: '02 - AI Content Processing & Script Generation'"
echo "  2. Click 'Execute Workflow' button (▶️)"
echo "  3. Wait 2-3 minutes (Ollama processing)"
echo "  4. Check results: cat ~/medicine/data/scripts/script_*.json"
echo ""
echo "📖 Need help? See: ~/medicine/SETUP-COMPLETE.md"
echo ""
echo "Opening n8n in browser..."
sleep 2
open http://localhost:5678
